# Generated by Django 5.1.1 on 2024-10-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0003_rename_name_usuario_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='idade',
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.CharField(default='usuario@cesar.school', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='matricula',
            field=models.CharField(default='12345', max_length=255),
        ),
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default='1234567', max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
