# Generated by Django 5.1 on 2024-10-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact', '0003_member_response_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='title',
            field=models.CharField(default='Novo FACT', max_length=200),
        ),
    ]
