# Generated by Django 5.1 on 2024-10-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact', '0004_fact_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='score',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')]),
        ),
    ]
