# Generated by Django 5.1 on 2024-10-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact', '0005_alter_response_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
