# Generated by Django 5.1 on 2024-10-31 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact', '0006_fact_is_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
